// Code generated by mockery v1.0.0
package mocks

import log "github.com/aws/amazon-ssm-agent/agent/log"
import mock "github.com/stretchr/testify/mock"

// IAmazonS3Util is an autogenerated mock type for the IAmazonS3Util type
type IAmazonS3Util struct {
	mock.Mock
}

// S3Upload provides a mock function with given fields: _a0, bucketName, objectKey, filePath
func (_m *IAmazonS3Util) S3Upload(_a0 log.T, bucketName string, objectKey string, filePath string) error {
	ret := _m.Called(_a0, bucketName, objectKey, filePath)

	var r0 error
	if rf, ok := ret.Get(0).(func(log.T, string, string, string) error); ok {
		r0 = rf(_a0, bucketName, objectKey, filePath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
